### ISSUE TITLE
Crash on Mobile Device

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/text#511]
Created a text document with an image.
- image (png) isn't displayed if you open the file.
- If you click on details the nextcloud app crashes.

Working on desktop.

**Comment by juliushaertl** [comment]
Please fill out the complete issue template and provide an example text file if possible

**Comment by axel-rank** [comment]
Just create a text document with or without image.
Open the document, click on details --> crash
Error message:

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:139)
at com.owncloud.android.utils.ThemeUtils.primaryColor(ThemeUtils.java:125)
at com.owncloud.android.ui.preview.PreviewTextFragment.getRenderedMarkdownText(PreviewTextFragment.java:284)
at com.owncloud.android.ui.preview.PreviewTextFragment.setText(PreviewTextFragment.java:562)
at com.owncloud.android.ui.preview.PreviewTextFragment.lambda$performSearch$0$PreviewTextFragment(PreviewTextFragment.java:270)
at com.owncloud.android.ui.preview.-$$Lambda$PreviewTextFragment$8cnNMZfHrJC_BSC1jdHMw1eFOds.run(lambda)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6236)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090290
Build flavor: gplay
