### ISSUE TITLE
403 on public share access

### ISSUE THREAD

**Issue by KarlKeu00** [nextcloud/text#5368]
**Describe the bug**
There is no way to deactivate the collaboration feature. When I share a folder and the end user is not authenticated, requests are still sent to `/apps/text/public/session/push`. These are rejected with 403 and lead to the user being blocked.

**To Reproduce**
1. Publish a folder in read-only mode for public access.
2. Open the link in an incognito window.
3. Go to the browser console and search for "push" in the requests.

**Expected behavior**
No request to push or the option to deactivate the collaboration feature.

**Screenshots**

**Server details:**
- Nextcloud version: 27.1.6
- PHP Version: Docker-Container (stable-apache)
- Database: MariaDB 10.6

**Client details:**
 - OS: macOS
 - Browser: Brave
 - Browser version: v1.62.156
 - Device: desktop

**Comment by KarlKeu00** [comment]
The following error also occurs:
```
TypeError: Cannot read properties of undefined (reading 'userId')
    at s.<anonymous> (Status.vue:1:857)
    at t._render (vue.runtime.esm.js:2700:28)
    at s.r (vue.runtime.esm.js:3891:27)
    at t.get (vue.runtime.esm.js:3462:33)
    at new t (vue.runtime.esm.js:3452:51)
    at t (vue.runtime.esm.js:3908:5)
    at li.$mount (vue.runtime.esm.js:8797:12)
    at init (vue.runtime.esm.js:4427:19)
    at vue.runtime.esm.js:6591:17
    at h (vue.runtime.esm.js:6545:13)
```
